@startuml

title __INTERFACES_LAB's Class Diagram__\n

  namespace  {
    class CDPlayer {
    }
  }
  

  namespace  {
    class CDPlayer {
    }
  }
  

  namespace  {
    class CDPlayerTest {
    }
  }
  

  namespace  {
    class CDPlayerTest {
    }
  }
  

  namespace  {
    abstract class Component {
    }
  }
  

  namespace  {
    abstract class Component {
    }
  }
  

  namespace  {
    interface IConnect {
    }
  }
  

  namespace  {
    interface IConnect {
    }
  }
  

  namespace  {
    class MP3Player {
    }
  }
  

  namespace  {
    class MP3Player {
    }
  }
  

  namespace  {
    class MP3PlayerTest {
    }
  }
  

  namespace  {
    class MP3PlayerTest {
    }
  }
  

  namespace  {
    enum PlaySpeed {
    }
  }
  

  namespace  {
    enum PlaySpeed {
    }
  }
  

  namespace  {
    class Radio {
    }
  }
  

  namespace  {
    class Radio {
    }
  }
  

  namespace  {
    class RadioTest {
    }
  }
  

  namespace  {
    class RadioTest {
    }
  }
  

  namespace  {
    class RecordDeck {
    }
  }
  

  namespace  {
    class RecordDeck {
    }
  }
  

  namespace  {
    class RecordDeckTest {
    }
  }
  

  namespace  {
    class RecordDeckTest {
    }
  }
  

  namespace  {
    class Stereo {
    }
  }
  

  namespace  {
    class Stereo {
    }
  }
  

  namespace  {
    class StereoTest {
    }
  }
  

  namespace  {
    class StereoTest {
    }
  }
  

  Component .up.|> IConnect
  Component .up.|> IConnect


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
